[package]
name = "finality-update-verify"
version = "0.1.0"
edition = "2021"

[dependencies]
eth-types = { path = "../../../pallet-eth2-light-client/crates/eth-types" }
consensus_types = { path = "../../../pallet-eth2-light-client/crates/consensus_types" }
bls = { path = "../../../pallet-eth2-light-client/crates/bls" }
tree_hash = { path = "../../../pallet-eth2-light-client/crates/tree_hash" }
bitvec = "1.0.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.74"
toml = "0.5.9"